"""briefs table

Revision ID: 2b4b842fba86
Revises: 870d08fc74cb
Create Date: 2026-05-17 10:51:04.208424+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2b4b842fba86'
down_revision: str | None = '870d08fc74cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('topic_title', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_org_id'), 'briefs', ['org_id'], unique=False)
    op.create_index(op.f('ix_briefs_user_id'), 'briefs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_briefs_user_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_org_id'), table_name='briefs')
    op.drop_table('briefs')
    # ### end Alembic commands ###
