"""rss_feeds + social_posts scope/region

Revision ID: fcfce23199b1
Revises: c3ae5a2dbedd
Create Date: 2026-05-18 02:19:42.984739+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fcfce23199b1'
down_revision: str | None = 'c3ae5a2dbedd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feeds', sa.Column('scope', sa.String(length=16), server_default=sa.text("'national'"), nullable=False))
    op.add_column('rss_feeds', sa.Column('region', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_rss_feeds_region'), 'rss_feeds', ['region'], unique=False)
    op.create_index(op.f('ix_rss_feeds_scope'), 'rss_feeds', ['scope'], unique=False)
    op.add_column('social_posts', sa.Column('region', sa.String(length=32), nullable=True))
    op.create_index('ix_social_posts_platform_region', 'social_posts', ['platform', 'region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_posts_platform_region', table_name='social_posts')
    op.drop_column('social_posts', 'region')
    op.drop_index(op.f('ix_rss_feeds_scope'), table_name='rss_feeds')
    op.drop_index(op.f('ix_rss_feeds_region'), table_name='rss_feeds')
    op.drop_column('rss_feeds', 'region')
    op.drop_column('rss_feeds', 'scope')
    # ### end Alembic commands ###
