"""social_posts table

Revision ID: d1a932a27791
Revises: 2b4b842fba86
Create Date: 2026-05-17 20:36:25.107136+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd1a932a27791'
down_revision: str | None = '2b4b842fba86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('dawah_relevance', sa.Float(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_social_post_platform_external')
    )
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index('ix_social_posts_platform_posted', 'social_posts', ['platform', 'posted_at'], unique=False)
    op.create_index(op.f('ix_social_posts_posted_at'), 'social_posts', ['posted_at'], unique=False)
    op.create_index('ix_social_posts_relevance', 'social_posts', ['dawah_relevance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_posts_relevance', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_posted_at'), table_name='social_posts')
    op.drop_index('ix_social_posts_platform_posted', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_table('social_posts')
    # ### end Alembic commands ###
