"""app_settings + seed usd_to_idr

Revision ID: a943d7488c61
Revises: 859ced351031
Create Date: 2026-05-18 03:16:45.860904+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a943d7488c61'
down_revision: str | None = '859ced351031'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # Seed the only setting we have right now — the USD→IDR display rate.
    op.execute(
        "INSERT INTO app_settings (key, value) VALUES ('usd_to_idr', '16300')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
