"""ingest_queries table

Revision ID: 74bf46ffd953
Revises: ef20c79feb51
Create Date: 2026-05-18 07:32:00.313420+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '74bf46ffd953'
down_revision: str | None = 'ef20c79feb51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_queries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('query', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Updated by the rotating task each time this query runs. NULL = never used; picked first on next rotation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'query', name='uq_ingest_query_platform')
    )
    op.create_index(op.f('ix_ingest_queries_platform'), 'ingest_queries', ['platform'], unique=False)
    op.create_index('ix_ingest_queries_platform_enabled', 'ingest_queries', ['platform', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingest_queries_platform_enabled', table_name='ingest_queries')
    op.drop_index(op.f('ix_ingest_queries_platform'), table_name='ingest_queries')
    op.drop_table('ingest_queries')
    # ### end Alembic commands ###
