"""rss_feeds.fetch_body

Revision ID: 4b087cde930d
Revises: fcfce23199b1
Create Date: 2026-05-18 02:33:07.289952+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4b087cde930d'
down_revision: str | None = 'fcfce23199b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feeds', sa.Column('fetch_body', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feeds', 'fetch_body')
    # ### end Alembic commands ###
