"""admin/observability tables

Revision ID: 770a8fe21b2b
Revises: d528fbb34eac
Create Date: 2026-05-17 21:39:20.522695+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '770a8fe21b2b'
down_revision: str | None = 'd528fbb34eac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_scraped', sa.Integer(), nullable=True),
    sa.Column('items_stored', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_runs_platform'), 'ingest_runs', ['platform'], unique=False)
    op.create_index(op.f('ix_ingest_runs_started_at'), 'ingest_runs', ['started_at'], unique=False)
    op.create_table('manual_costs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_idr', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_costs_kind'), 'manual_costs', ['kind'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_occurred_at'), 'page_views', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_page_views_path'), 'page_views', ['path'], unique=False)
    op.create_table('rss_feeds',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_rss_feed_name')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=False),
    sa.Column('mem_used_mb', sa.Float(), nullable=False),
    sa.Column('mem_total_mb', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('load_1m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_captured_at'), 'system_metrics', ['captured_at'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_occurred_at'), 'usage_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_events_provider'), 'usage_events', ['provider'], unique=False)
    op.create_index('ix_usage_events_provider_time', 'usage_events', ['provider', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_provider_time', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_provider'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_occurred_at'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_system_metrics_captured_at'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('rss_feeds')
    op.drop_index(op.f('ix_page_views_path'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_occurred_at'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_manual_costs_kind'), table_name='manual_costs')
    op.drop_table('manual_costs')
    op.drop_index(op.f('ix_ingest_runs_started_at'), table_name='ingest_runs')
    op.drop_index(op.f('ix_ingest_runs_platform'), table_name='ingest_runs')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
