"""user profile + onboarded_at

Revision ID: c3ae5a2dbedd
Revises: 770a8fe21b2b
Create Date: 2026-05-18 01:46:12.456268+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c3ae5a2dbedd'
down_revision: str | None = '770a8fe21b2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the user finishes the /onboarding wizard.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded_at')
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
