"""topics table + social_posts.topic_id

Revision ID: d528fbb34eac
Revises: d1a932a27791
Create Date: 2026-05-17 21:16:59.156378+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd528fbb34eac'
down_revision: str | None = 'd1a932a27791'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_platform'), 'topics', ['platform'], unique=False)
    op.create_index('ix_topics_platform_postcount', 'topics', ['platform', 'post_count'], unique=False)
    op.add_column('social_posts', sa.Column('topic_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_social_posts_topic_id'), 'social_posts', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'social_posts', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_posts', type_='foreignkey')
    op.drop_index(op.f('ix_social_posts_topic_id'), table_name='social_posts')
    op.drop_column('social_posts', 'topic_id')
    op.drop_index('ix_topics_platform_postcount', table_name='topics')
    op.drop_index(op.f('ix_topics_platform'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
