/**
 * Flash-Lite content writer for user-generated flyers.
 *
 * Takes the user's free-text intent + optional news context and emits
 * a structured (headline, body, search_theme) triple. The `search_theme`
 * is then fed to `searchKitabBrowse` so the daleel comes from the
 * verified Qdrant corpus — per PRD §12, daleel is RETRIEVED, never
 * generated by the LLM.
 *
 * Cost: ~$0.0005 per call (Flash-Lite, ~600 tokens in / ~200 out).
 */

import { GoogleGenAI, Type } from "@google/genai";

import { formatCalendarContext } from "@/lib/islamic-calendar";
import { recordUsage } from "@/lib/usage-log";

export type UserFlyerContent = {
  headline: string;
  body: string;
  /** Indonesian phrase used as the Qdrant search query for daleel. */
  searchTheme: string;
};

export type NewsContext = {
  /** "akhlaq" | "social_justice" | etc. */
  topCategory: string;
  /** Short list of trending topic labels this week. */
  topTopics: string[];
};

export class FlyerGenUnavailableError extends Error {
  constructor() {
    super("GEMINI_API_KEY is not configured.");
    this.name = "FlyerGenUnavailableError";
  }
}

let _client: GoogleGenAI | null = null;
function getClient(): GoogleGenAI {
  if (!process.env.GEMINI_API_KEY) throw new FlyerGenUnavailableError();
  if (_client === null) {
    _client = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }
  return _client;
}

const SYSTEM_PROMPT = `Anda menulis copy untuk flyer dakwah 1080×1080 yang dibagikan ke IG Story / WA / grup pengajian — audiens umum Muslim Indonesia (da'i, ustadzah, content creator, orang tua, organizer komunitas).

ATURAN PENULISAN:
- Bahasa: Indonesia. JANGAN gunakan English.
- Headline: 4-8 kata, punchy, ajakan / refleksi / pertanyaan terbuka. Hindari kata "wajib" untuk amalan sunnah.
- Body: 40-70 kata, satu paragraf, mengalir natural. Sebutkan konkret yang bisa dilakukan pembaca. JANGAN menggurui ("Anda harus...", "wahai..."). Pakai "kita", "mari".
- Tone: hangat, mengajak, hikmah > judgment. Promosikan rahma (kasih sayang) dan hikmah (kebijaksanaan).
- JANGAN tulis ayat / hadits di body — daleel akan disisipkan terpisah lewat retrieval dari kitab corpus. Anda hanya menulis copy temanya.
- JANGAN sebut nama penerjemah, lembaga, atau gaya kitab.
- Hindari content yang sektarian / menyalahkan manhaj lain.

OUTPUT JSON:
- headline: string (4-8 kata)
- body: string (40-70 kata)
- search_theme: 1 kalimat Indonesia (max 25 kata) yang menggambarkan tema syar'i dari flyer — akan dipakai untuk mencari ayat/hadits yang cocok di basis data vektor. Gunakan kosakata syar'i (rahma, hikmah, sabar, tawakkul, amanah, ihsan, tazkiyatun nafs, dzikir, takwa, dll.) yang biasa muncul dalam terjemahan ayat/hadits.`;

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    headline: { type: Type.STRING },
    body: { type: Type.STRING },
    search_theme: { type: Type.STRING },
  },
  required: ["headline", "body", "search_theme"],
};

export async function generateUserFlyerContent({
  userPrompt,
  news,
}: {
  userPrompt: string;
  news: NewsContext | null;
}): Promise<UserFlyerContent> {
  const client = getClient();

  // Hijri calendar awareness — same helper the brief generator + Insights
  // pipeline use. Without this the LLM has no idea what TODAY is in the
  // Hijri calendar and inferred-date errors slip in (e.g. saying "Arafah
  // is coming soon" when today IS Arafah).
  const { promptBlock: calendarBlock } = formatCalendarContext(
    new Date(),
    10,
  );

  const newsBlock = news
    ? `\n\nKONTEKS BERITA PEKAN INI (gunakan sebagai LATAR / pemicu, jangan ulang fakta-fakta-nya — pembaca sudah tahu beritanya):\n- Kategori dominan: ${news.topCategory}\n- Topik trending: ${news.topTopics.slice(0, 5).join("; ")}`
    : "";

  const userBlock = `${calendarBlock}

PERMINTAAN PENGGUNA (free text, mungkin singkat atau samar — silakan tafsirkan dengan baik):
"""
${userPrompt.trim()}
"""${newsBlock}

Tulis copy flyer sesuai aturan di atas. Pastikan headline + body KONSISTEN dengan konteks kalender Hijriyah di atas (kalau hari ini adalah event tertentu, jangan menulis "akan datang" atau "sebentar lagi"). Output WAJIB JSON dengan field headline, body, search_theme.`;

  const resp = await client.models.generateContent({
    model: "gemini-2.5-flash-lite",
    contents: userBlock,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      temperature: 0.7,
      maxOutputTokens: 600,
      thinkingConfig: { thinkingBudget: 0 },
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
    },
  });

  void recordUsage({
    provider: "gemini",
    operation: "user_flyer_content_gen",
    model: "gemini-2.5-flash-lite",
    tokensIn: resp.usageMetadata?.promptTokenCount ?? null,
    tokensOut: resp.usageMetadata?.candidatesTokenCount ?? null,
  });

  const raw = resp.text ?? "";
  let parsed: Partial<UserFlyerContent> & { search_theme?: string };
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Flash-Lite returned non-JSON output: " + raw.slice(0, 200));
  }

  const headline = (parsed.headline ?? "").trim();
  const body = (parsed.body ?? "").trim();
  const searchTheme = (parsed.search_theme ?? "").trim();
  if (!headline || !body || !searchTheme) {
    throw new Error("Flash-Lite missing required fields in output.");
  }

  return { headline, body, searchTheme };
}
