/**
 * Flash-Lite content writer for user-generated flyers.
 *
 * Takes the user's free-text intent + optional news context and emits
 * a structured (headline, body, search_theme) triple. The `search_theme`
 * is then fed to `searchKitabBrowse` so the daleel comes from the
 * verified Qdrant corpus — per PRD §12, daleel is RETRIEVED, never
 * generated by the LLM.
 *
 * Cost: ~$0.0005 per call (Flash-Lite, ~600 tokens in / ~200 out).
 */

import { GoogleGenAI, Type } from "@google/genai";

import { formatCalendarContext } from "@/lib/islamic-calendar";
import { recordUsage } from "@/lib/usage-log";

export type UserFlyerContent = {
  headline: string;
  body: string;
  /** Indonesian phrase used as the Qdrant search query for daleel. */
  searchTheme: string;
};

export type NewsContext = {
  /** "akhlaq" | "social_justice" | etc. — OR, when the caller hydrated
   *  from a specific picked topic, that topic's label (so the prompt's
   *  "Kategori dominan" line still has a meaningful anchor). */
  topCategory: string;
  /** Short list of trending topic labels this week. */
  topTopics: string[];
  /** When the user picked a specific topic from the dropdown, these
   *  fields carry that topic's actual signal. The prompt branches: if
   *  `pickedLabel` is set it renders a tighter "ground in this
   *  specific conversation" block instead of the broad-aggregate one. */
  pickedLabel?: string;
  pickedKeywords?: string[];
  pickedSampleHeadlines?: string[];
};

export class FlyerGenUnavailableError extends Error {
  constructor() {
    super("GEMINI_API_KEY is not configured.");
    this.name = "FlyerGenUnavailableError";
  }
}

let _client: GoogleGenAI | null = null;
function getClient(): GoogleGenAI {
  if (!process.env.GEMINI_API_KEY) throw new FlyerGenUnavailableError();
  if (_client === null) {
    _client = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }
  return _client;
}

const SYSTEM_PROMPT = `Anda menulis copy untuk flyer dakwah 1080×1080 yang dibagikan ke IG Story / WA / grup pengajian — audiens umum Muslim Indonesia (da'i, ustadzah, content creator, orang tua, organizer komunitas).

ATURAN PENULISAN:
- Bahasa: Indonesia. JANGAN gunakan English.
- Headline: 4-8 kata, punchy, ajakan / refleksi / pertanyaan terbuka. Hindari kata "wajib" untuk amalan sunnah.
- Body: 40-70 kata, satu paragraf, mengalir natural. Sebutkan konkret yang bisa dilakukan pembaca. JANGAN menggurui ("Anda harus...", "wahai..."). Pakai "kita", "mari".
- Tone: hangat, mengajak, hikmah > judgment. Promosikan rahma (kasih sayang) dan hikmah (kebijaksanaan).
- JANGAN tulis ayat / hadits di body — daleel akan disisipkan terpisah lewat retrieval dari kitab corpus. Anda hanya menulis copy temanya.
- JANGAN sebut nama penerjemah, lembaga, atau gaya kitab.
- Hindari content yang sektarian / menyalahkan manhaj lain.

OUTPUT JSON:
- headline: string (4-8 kata)
- body: string (40-70 kata)
- search_theme: 1 kalimat Indonesia (max 25 kata) yang menggambarkan tema syar'i dari flyer — akan dipakai untuk mencari ayat/hadits yang cocok di basis data vektor. Gunakan kosakata syar'i (rahma, hikmah, sabar, tawakkul, amanah, ihsan, tazkiyatun nafs, dzikir, takwa, dll.) yang biasa muncul dalam terjemahan ayat/hadits.`;

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    headline: { type: Type.STRING },
    body: { type: Type.STRING },
    search_theme: { type: Type.STRING },
  },
  required: ["headline", "body", "search_theme"],
};

/** Tone presets — mirrored from the brief generator so a da'i moving
 *  between brief + flyer flows sees the same vocabulary. */
export type FlyerTone =
  | "scholarly"
  | "casual"
  | "motivational"
  | "empathetic"
  | "fiery"
  | "gentle";

/** Audience segments — also mirrored from the brief generator. */
export type FlyerAudience =
  | "general"
  | "urban_gen_z"
  | "working_professionals"
  | "parents_families"
  | "ibu_pengajian"
  | "rural_communities"
  | "students";

const TONE_HINT_ID: Record<FlyerTone, string> = {
  scholarly: "ilmiah dan terukur — kutip rujukan secara tersirat, hindari jargon akademis",
  casual: "santai dan hangat, seperti obrolan WhatsApp dengan teman",
  motivational: "memotivasi dan present-tense, beri urgensi tanpa menggurui",
  empathetic: "lembut dan empatik, akui kesulitan pembaca dulu sebelum menasihati",
  fiery: "tegas dan menggugah, langsung ke akar masalah",
  gentle: "lembut dan tenang, beri ruang untuk pembaca merenung sendiri",
};

const AUDIENCE_HINT_ID: Record<FlyerAudience, string> = {
  general: "umum Muslim Indonesia — register netral",
  urban_gen_z: "Gen Z perkotaan (18-26 th) — bahasa kasual, contoh anxiety karier / media sosial / krisis identitas; light Gen Z markers (relate, vibes, FOMO) OK",
  working_professionals: "profesional muda (25-40 th) — fokus etika kerja, manajemen waktu, ihtisab di tempat kerja, tekanan finansial",
  parents_families: "orang tua + keluarga — fokus pendidikan anak, hak suami-istri, dinamika antar-generasi, tarbiyah keluarga",
  ibu_pengajian: "ibu-ibu majelis taklim — bahasa hangat, contoh keseharian rumah tangga, doa praktis untuk anak",
  rural_communities: "komunitas pedesaan — bahasa sederhana, contoh konkret dari kehidupan agraris/pesisir, jangan pakai jargon kota",
  students: "pelajar/mahasiswa — fokus integritas akademik, persiapan masa depan, peer pressure, godaan judol/pinjol",
};

export async function generateUserFlyerContent({
  userPrompt,
  news,
  tone,
  audience,
}: {
  userPrompt: string;
  news: NewsContext | null;
  tone?: FlyerTone;
  audience?: FlyerAudience;
}): Promise<UserFlyerContent> {
  const client = getClient();

  // Hijri calendar awareness — same helper the brief generator + Insights
  // pipeline use. Without this the LLM has no idea what TODAY is in the
  // Hijri calendar and inferred-date errors slip in (e.g. saying "Arafah
  // is coming soon" when today IS Arafah).
  const { promptBlock: calendarBlock } = formatCalendarContext(
    new Date(),
    10,
  );

  const newsBlock = (() => {
    if (!news) return "";
    if (news.pickedLabel && news.pickedSampleHeadlines && news.pickedSampleHeadlines.length > 0) {
      // User picked a specific current topic → ground the flyer in
      // concrete headlines from that topic instead of the broad
      // top-category + 5-trending blob.
      const kwLine = news.pickedKeywords && news.pickedKeywords.length > 0
        ? `\n- Kata kunci: ${news.pickedKeywords.join(", ")}`
        : "";
      const headlines = news.pickedSampleHeadlines
        .map((h, i) => `  ${i + 1}. ${h}`)
        .join("\n");
      return `\n\nKONTEKS TOPIK PEKAN INI (pengguna memilih topik ini sebagai pemicu — gunakan headline di bawah sebagai LATAR konkret, jangan ulang fakta-fakta-nya verbatim, JANGAN sebut nama outlet media):\n- Topik: "${news.pickedLabel}"${kwLine}\n- Sample headline:\n${headlines}`;
    }
    return `\n\nKONTEKS BERITA PEKAN INI (gunakan sebagai LATAR / pemicu, jangan ulang fakta-fakta-nya — pembaca sudah tahu beritanya):\n- Kategori dominan: ${news.topCategory}\n- Topik trending: ${news.topTopics.slice(0, 5).join("; ")}`;
  })();

  // Tone + audience hints are short directives the LLM weights when
  // writing the headline + body. Both default to neutral when omitted
  // so existing callers (and existing flyers re-rendered later) keep
  // their historical behaviour.
  const styleBlock = tone || audience
    ? "\n\nGAYA + AUDIENS:" +
      (tone ? `\n- Tone: ${TONE_HINT_ID[tone]}` : "") +
      (audience ? `\n- Audiens: ${AUDIENCE_HINT_ID[audience]}` : "")
    : "";

  const userBlock = `${calendarBlock}

PERMINTAAN PENGGUNA (free text, mungkin singkat atau samar — silakan tafsirkan dengan baik):
"""
${userPrompt.trim()}
"""${newsBlock}${styleBlock}

Tulis copy flyer sesuai aturan di atas. Pastikan headline + body KONSISTEN dengan konteks kalender Hijriyah di atas (kalau hari ini adalah event tertentu, jangan menulis "akan datang" atau "sebentar lagi"). Output WAJIB JSON dengan field headline, body, search_theme.`;

  const resp = await client.models.generateContent({
    model: "gemini-2.5-flash-lite",
    contents: userBlock,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      temperature: 0.7,
      maxOutputTokens: 600,
      thinkingConfig: { thinkingBudget: 0 },
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
    },
  });

  void recordUsage({
    provider: "gemini",
    operation: "user_flyer_content_gen",
    model: "gemini-2.5-flash-lite",
    tokensIn: resp.usageMetadata?.promptTokenCount ?? null,
    tokensOut: resp.usageMetadata?.candidatesTokenCount ?? null,
  });

  const raw = resp.text ?? "";
  let parsed: Partial<UserFlyerContent> & { search_theme?: string };
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Flash-Lite returned non-JSON output: " + raw.slice(0, 200));
  }

  const headline = (parsed.headline ?? "").trim();
  const body = (parsed.body ?? "").trim();
  const searchTheme = (parsed.search_theme ?? "").trim();
  if (!headline || !body || !searchTheme) {
    throw new Error("Flash-Lite missing required fields in output.");
  }

  return { headline, body, searchTheme };
}
