/**
 * Default Indonesian copy for the questionnaire (plan §5; ux.md §4.3 wording, with the §5.7
 * changes). The UI copies these into messages/waris/id.json under its own namespace, keyed
 * exactly as here; machine.ts views only ever hand out these keys.
 *
 * Rules for every string (checked by checks/questionnaire.ts):
 *  - "Anda" register, sentence case, no ALL-CAPS emphasis;
 *  - no Islamic citation as bare text ("QS …", "HR …"): a reference goes through the node's
 *    `why` RuleIds, whose RuleNotes carry the dalil (plan D10);
 *  - no Arabic script (every Arabic string is a byte slice of dalil.json, shown by the RuleNote);
 *  - nothing promises or reports a review by an ustadz (there is no human review, plan §2);
 *  - placeholders: {pewaris} {Pewaris} {saat} {Saat} {pasangan} {Pasangan} (machine.messageVars),
 *    {kelompok} {penghalang} (skip lines).
 * AI-assisted, not an authoritative fatwa.
 */
export const Q_TEXT = {
  // --- common ---------------------------------------------------------------------------
  "umum.tidak_tahu": "Tidak tahu",
  "umum.tidak_ada": "Tidak ada",
  "umum.ya": "Ya",
  "umum.tidak": "Tidak",
  "umum.laki": "Laki-laki",
  "umum.perempuan": "Perempuan",
  "umum.lanjut": "Lanjut",
  "umum.kembali": "Kembali",
  "umum.ubah": "Ubah",
  "umum.ubah_jawaban": "Ubah jawaban",
  "umum.cetak_ringkasan": "Cetak ringkasan jawaban Anda",
  "umum.kembali_pelajaran": "Kembali ke pelajaran",
  "umum.mengapa": "Kenapa kami tanyakan ini?",
  "umum.pertanyaan_baru": "Ada pertanyaan baru karena perubahan Anda.",
  "umum.hint_wafat_setelah": "Jika ada yang wafat setelah {pewaris}, sebelum harta dibagi, tetap hitung dia.",
  "umum.ringkasan_judul": "Apakah ini sudah benar?",
  "umum.lihat_laporan": "Lihat rekomendasi pembagian",

  // --- sections (progress without a total) -----------------------------------------------
  "bagian.pewaris": "Pewaris",
  "bagian.pasangan": "Pasangan",
  "bagian.anak": "Anak",
  "bagian.orang_tua": "Orang tua",
  "bagian.saudara": "Saudara",
  "bagian.kerabat": "Kerabat lain",
  "bagian.wasiat": "Wasiat",

  // --- A. Pewaris --------------------------------------------------------------------------
  "A1.tanya": "Untuk siapa Anda menghitung?",
  "A1.mengapa": "Hukum waris Islam berlaku untuk harta seorang Muslim yang sudah wafat. Pembagian semasa hidup disebut hibah, bukan waris.",
  "A1.opsi.wafat_muslim": "Keluarga Muslim yang sudah wafat",
  "A1.opsi.saya_hidup": "Saya sendiri, masih hidup (ingin merencanakan)",
  "A1.opsi.simulasi_keluarga": "Orang tua atau keluarga saya yang masih hidup (simulasi)",
  "A1.opsi.wafat_nonmuslim": "Keluarga yang wafat bukan Muslim",
  "A1s.tanya": "Lanjutkan sebagai simulasi: jika saya wafat hari ini",
  "A1s.mengapa": "Simulasi menunjukkan bagaimana harta Anda akan dibagi jika Anda wafat hari ini. Laporannya diberi tanda simulasi.",
  "A1s.opsi.ya": "Lanjutkan sebagai simulasi",
  "A2.tanya": "{Pewaris} seorang laki-laki atau perempuan?",
  "A2.mengapa": "Ini menentukan apakah yang ditinggalkan seorang suami atau istri, dan besar bagian masing-masing.",
  "A2.opsi.L": "Laki-laki",
  "A2.opsi.P": "Perempuan",
  "A3.tanya": "Apakah ada keadaan khusus berikut?",
  "A3.mengapa": "Beberapa keadaan mengubah cara menghitung. Kebanyakan keluarga cukup memilih “Tidak ada satu pun”.",
  "A3.bantuan": "Ada ahli waris yang wafat setelah {pewaris}, sebelum harta dibagi? Tetap masukkan dia sebagai orang yang hidup.",
  "A3.opsi.k0": "Tidak ada satu pun",
  "A3.opsi.k1": "Ada anggota keluarga yang berbeda agama {saat}, termasuk anak yang wafat lebih dulu",
  "A3.opsi.k2": "{Pewaris} mempunyai anak angkat",
  "A3.opsi.k3": "Ada anggota keluarga yang hilang, belum jelas masih hidup atau sudah wafat",
  "A3.opsi.k4": "Ada bayi dalam kandungan di keluarga ini, misalnya istri atau menantu yang sedang hamil",
  "A3.opsi.k5": "Beberapa anggota keluarga wafat dalam satu musibah, dan tidak diketahui siapa yang lebih dulu",
  "A3.opsi.k6": "Ada anggota keluarga yang menyebabkan wafatnya {pewaris}, atau dihukum karena mencoba membunuh atau menganiaya berat {pewaris}",
  "A3.opsi.k7": "Ada anggota keluarga yang jenis kelaminnya tidak dapat dipastikan sejak lahir",
  "A3.opsi.k8": "Ada anak tiri yang diasuh {pewaris}",
  "A3.opsi.k9": "Ada istri, suami, atau anak dari pernikahan yang tidak dicatat (nikah siri)",
  "A3a.tanya": "Di kelompok mana ada yang berbeda agama {saat}?",
  "A3a.mengapa": "Kerabat yang berbeda agama tidak saling mewarisi, tetapi tetap bisa diberi hibah atau wasiat. Kami menanyakan agama hanya pada kelompok yang Anda pilih.",
  "A3a.opsi.pasangan": "Istri atau suami",
  "A3a.opsi.anak": "Anak",
  "A3a.opsi.cucu": "Cucu dan keturunannya",
  "A3a.opsi.orang_tua": "Ayah atau ibu",
  "A3a.opsi.kakek_nenek": "Kakek atau nenek",
  "A3a.opsi.saudara": "Saudara",
  "A3a.opsi.kerabat": "Keponakan, paman, atau sepupu",
  "A3b.tanya": "Berapa anak angkat {pewaris}?",
  "A3b.mengapa": "Anak angkat bukan ahli waris, tetapi Pengadilan Agama dapat menetapkan wasiat wajibah untuknya.",
  "A3b2.tanya": "Apakah pengangkatan anak ini berdasarkan penetapan pengadilan?",
  "A3b2.mengapa": "Menurut Kompilasi Hukum Islam, anak angkat yang diakui adalah yang diangkat berdasarkan putusan pengadilan.",
  "A3b2.opsi.ya": "Ya",
  "A3b2.opsi.tidak": "Tidak",
  "A3b2.opsi.sebagian": "Sebagian",
  "A3b3.tanya": "Berapa yang diangkat berdasarkan penetapan pengadilan?",
  "A3b3.mengapa": "Wasiat wajibah hanya dihitung untuk anak angkat dengan penetapan pengadilan.",
  "A3b4.tanya": "Apakah {pewaris} sudah memberi wasiat kepada anak angkat itu?",
  "A3b4.mengapa": "Anak angkat yang sudah menerima wasiat tidak lagi mendapat wasiat wajibah.",
  "A3b4.opsi.ya": "Ya, sudah",
  "A3b4.opsi.tidak": "Belum",
  "A3c.tanya": "Siapa anggota keluarga yang hilang itu?",
  "A3c.mengapa": "Setelah semua keluarga dimasukkan, kami periksa apakah orang ini bisa mengubah pembagian. Perhitungan berhenti hanya jika bisa.",
  "A3d.tanya": "Bayi dalam kandungan itu, jika lahir, akan menjadi siapa bagi {pewaris}?",
  "A3d.mengapa": "Setelah semua keluarga dimasukkan, kami periksa apakah bayi ini bisa mengubah pembagian. Perhitungan berhenti hanya jika bisa.",
  "A3e.tanya": "Siapa yang wafat dalam musibah yang sama dengan {pewaris}?",
  "A3e.mengapa": "Setelah semua keluarga dimasukkan, kami periksa apakah orang ini bisa mengubah pembagian. Perhitungan berhenti hanya jika bisa.",
  "A3c.opsi.pasangan": "Istri atau suami",
  "A3c.opsi.anak": "Anak",
  "A3c.opsi.cucu": "Cucu",
  "A3c.opsi.ayah": "Ayah",
  "A3c.opsi.ibu": "Ibu",
  "A3c.opsi.kakek": "Kakek",
  "A3c.opsi.nenek": "Nenek",
  "A3c.opsi.saudara": "Saudara",
  "A3c.opsi.kerabat": "Keponakan, paman, atau sepupu",
  "A3d.opsi.anak": "Anak {pewaris}",
  "A3d.opsi.cucu": "Cucu {pewaris}",
  "A3d.opsi.saudara": "Saudara {pewaris}",
  "A3d.opsi.kerabat": "Keponakan atau sepupu {pewaris}",
  "A3e.opsi.pasangan": "Istri atau suami",
  "A3e.opsi.anak": "Anak",
  "A3e.opsi.cucu": "Cucu",
  "A3e.opsi.ayah": "Ayah",
  "A3e.opsi.ibu": "Ibu",
  "A3e.opsi.kakek": "Kakek",
  "A3e.opsi.nenek": "Nenek",
  "A3e.opsi.saudara": "Saudara",
  "A3e.opsi.kerabat": "Keponakan, paman, atau sepupu",

  // --- B. Pasangan -------------------------------------------------------------------------
  "B1.tanya": "{Saat}, apakah {pewaris} masih mempunyai {pasangan}?",
  "B1.mengapa": "{Pasangan} mendapat bagian dan tidak terhalang oleh kerabat lain, kecuali bila berbeda agama atau ada penghalang.",
  "B1.bantuan": "Termasuk pernikahan yang tidak dicatat (nikah siri).",
  "B1.opsi.ya_satu": "Ya, satu istri",
  "B1.opsi.ya_satu_P": "Ya, suami masih hidup",
  "B1.opsi.ya_lebih": "Ya, lebih dari satu istri",
  "B1.opsi.iddah": "Bercerai, dan {pewaris} wafat dalam masa iddah talak raj'i",
  "B1.opsi.pernah": "Tidak, tetapi pernah menikah",
  "B1.opsi.belum": "Tidak, belum pernah menikah",
  "B2.tanya": "Berapa istri {pewaris} {saat}?",
  "B2.mengapa": "Para istri berbagi satu bagian yang sama, seperempat atau seperdelapan.",
  "B3.tanya": "Berapa di antara para istri yang beragama Islam {saat}?",
  "B3.tanya_satu": "Apakah {pasangan} {pewaris} beragama Islam {saat}?",
  "B3.mengapa": "Pasangan yang berbeda agama tidak saling mewarisi. Islam tetap membuka jalan kebaikan untuknya melalui hibah atau wasiat.",
  "B1b.tanya": "Pernahkah ada {pasangan} lain yang wafat lebih dulu atau bercerai dengan {pewaris}?",
  "B1b.tanya_pernah": "Apakah masih ada harta bersama dari pernikahan {pewaris} dahulu yang belum dibagi?",
  "B1b.mengapa": "Harta bersama dari pernikahan sebelumnya perlu dipisahkan dulu. Pembagian tetap dihitung; nilai rupiah harta bersama akan dirujuk ke pengadilan.",
  "B1b.opsi.ya": "Ya",
  "B1b.opsi.tidak": "Tidak",

  // --- C. Anak -----------------------------------------------------------------------------
  "C1.tanya": "Berapa anak kandung {pewaris} yang masih hidup {saat}?",
  "C1.mengapa": "Anak adalah ahli waris terdekat. Adanya anak juga mengubah bagian pasangan dan orang tua.",
  "C1.bantuan": "Termasuk anak dari pernikahan sebelumnya dan dari pernikahan yang tidak dicatat. Anak tiri dan anak angkat tidak dihitung di sini.",
  "C1m.tanya": "Berapa di antara anak-anak itu yang beragama Islam {saat}?",
  "C1m.mengapa": "Hanya anak yang seagama yang mewarisi; yang lain tetap bisa diberi hibah atau wasiat.",
  "C1n.tanya": "Berapa anak dari anak laki-laki yang tidak beragama Islam itu (cucu {pewaris}) yang beragama Islam dan masih hidup {saat}?",
  "C1n.mengapa": "Anak yang berbeda agama tidak mewarisi dan tidak menghalangi anak-anaknya sendiri. Cucu dari anak laki-laki itu bisa mendapat bagian.",
  "C1p.tanya": "Berapa anak dari anak perempuan yang tidak beragama Islam itu (cucu {pewaris}) yang beragama Islam dan masih hidup {saat}?",
  "C1p.mengapa": "Anak yang berbeda agama tidak menghalangi anak-anaknya sendiri. Cucu dari anak perempuan termasuk kerabat yang perhitungannya khusus.",
  "C3.tanya": "Apakah ada anak {pewaris} yang wafat lebih dulu dan meninggalkan anak atau cucu?",
  "C3.mengapa": "Cucu dari anak yang wafat lebih dulu bisa mendapat bagian. Caranya berbeda antara fikih dan Kompilasi Hukum Islam, jadi kami menanyakannya untuk keduanya.",
  "C3.bantuan": "Anak yang wafat setelah {pewaris} tetap dihitung sebagai anak yang hidup.",
  "C3.opsi.ya": "Ya",
  "C3.opsi.tidak": "Tidak",
  "C4s.tanya": "Anak {pewaris} yang wafat lebih dulu itu laki-laki atau perempuan?",
  "C4s.mengapa": "Fikih membedakan cucu dari anak laki-laki dan dari anak perempuan; Kompilasi Hukum Islam menempatkan cucu di posisi orang tuanya.",
  "C4s.opsi.L": "Laki-laki",
  "C4s.opsi.P": "Perempuan",
  "C4r.tanya": "Apakah anak itu beragama Islam ketika ia wafat?",
  "C4r.mengapa": "Menurut Kompilasi Hukum Islam, cucu menggantikan orang tuanya hanya bila orang tuanya seorang Muslim.",
  "C4r.opsi.ya": "Ya",
  "C4r.opsi.tidak": "Tidak",
  "C4g.tanya": "Berapa anak dari anak itu (cucu {pewaris}) yang masih hidup {saat}?",
  "C4g.mengapa": "Cucu inilah yang bisa menggantikan posisi orang tuanya.",
  "C4gm.tanya": "Berapa di antara cucu itu yang beragama Islam {saat}?",
  "C4gm.mengapa": "Hanya cucu yang seagama yang mewarisi.",
  "C4b.tanya": "Apakah ada keturunan lain dari anak itu yang perlu kami ketahui?",
  "C4b.muslim.tanya": "Apakah ada keturunan lain dari anak itu, yang beragama Islam, yang perlu kami ketahui?",
  "C4b.mengapa": "Alat ini menghitung sampai cucu. Bila keturunan yang lebih jauh bisa mengubah pembagian, kami akan menyarankan konsultasi.",
  "C4b.opsi.keturunan_jauh_L": "Ada cucu laki-laki yang juga wafat lebih dulu dan meninggalkan keturunan",
  "C4b.opsi.keturunan_jauh_P": "Ada cucu yang juga wafat lebih dulu dan meninggalkan keturunan",
  "C4b.opsi.anak_cucu_perempuan": "Ada cucu perempuan yang wafat lebih dulu dan meninggalkan anak",
  "C4b.opsi.cicit_dari_cucu_hidup": "Ada cucu yang masih hidup dan sudah mempunyai anak",
  "C4m.tanya": "Apakah ada anak {pewaris} lain yang wafat lebih dulu dan meninggalkan anak atau cucu?",
  "C4m.mengapa": "Setiap anak yang wafat lebih dulu dihitung terpisah, bersama cucu-cucunya.",
  "C4m.opsi.ya": "Ya",
  "C4m.opsi.tidak": "Tidak",

  // --- D. Orang tua ------------------------------------------------------------------------
  "D1.tanya": "Siapa orang tua {pewaris} yang masih hidup {saat}?",
  "D1.mengapa": "Ayah dan ibu mendapat bagian dan tidak terhalang oleh kerabat lain, kecuali bila berbeda agama atau ada penghalang. Ayah juga menghalangi kakek dan saudara.",
  "D1.opsi.keduanya": "Ayah dan ibu",
  "D1.opsi.ayah": "Hanya ayah",
  "D1.opsi.ibu": "Hanya ibu",
  "D1.opsi.tidak_ada": "Keduanya sudah wafat",
  "D1m.tanya": "Siapa di antara mereka yang beragama Islam {saat}?",
  "D1m.tanya_satu": "Apakah orang tua {pewaris} itu beragama Islam {saat}?",
  "D1m.mengapa": "Orang tua yang berbeda agama tidak mewarisi, tetapi tetap bisa diberi hibah atau wasiat.",
  "D1m.opsi.keduanya": "Ayah dan ibu",
  "D1m.opsi.ayah": "Hanya ayah",
  "D1m.opsi.ibu": "Hanya ibu",
  "D1m.opsi.tidak_ada": "Tidak ada",
  "D1m.opsi.ya_satu": "Ya",
  "D1m.opsi.tidak_satu": "Tidak",
  "D3.tanya": "Siapa kakek atau nenek {pewaris} yang masih hidup {saat}?",
  "D3.mengapa": "Kakek dan nenek menempati posisi ayah atau ibu yang sudah tiada. Ibu menghalangi semua nenek; ayah menghalangi kakek dan nenek dari pihak ayah.",
  "D3.bantuan": "Kakek dari pihak ibu (ayah dari ibu) tidak termasuk di sini. Kami hanya menanyakan yang bisa mengubah pembagian.",
  "D3.opsi.kakek": "Kakek (ayah dari ayah)",
  "D3.opsi.nenek_ibu": "Nenek (ibu dari ibu)",
  "D3.opsi.nenek_ayah": "Nenek (ibu dari ayah)",
  "D3m.tanya": "Siapa di antara mereka yang beragama Islam {saat}?",
  "D3m.mengapa": "Kakek atau nenek yang berbeda agama tidak mewarisi.",
  "D3m.opsi.kakek": "Kakek (ayah dari ayah)",
  "D3m.opsi.nenek_ibu": "Nenek (ibu dari ibu)",
  "D3m.opsi.nenek_ayah": "Nenek (ibu dari ayah)",

  // --- E. Saudara --------------------------------------------------------------------------
  "E1.tanya": "Berapa saudara kandung (seayah dan seibu) {pewaris} yang masih hidup {saat}?",
  "E1.mengapa": "Saudara bisa mendapat bagian bila tidak ada anak laki-laki dan ayah. Walaupun terhalang, dua saudara atau lebih tetap mengurangi bagian ibu.",
  "E1m.tanya": "Berapa di antara saudara kandung itu yang beragama Islam {saat}?",
  "E1m.mengapa": "Hanya saudara yang seagama yang mewarisi atau mengurangi bagian ibu.",
  "E2.tanya": "Berapa saudara seayah (lain ibu) {pewaris} yang masih hidup {saat}?",
  "E2.mengapa": "Saudara seayah mendapat bagian bila tidak ada saudara laki-laki kandung. Bersama kakek, mereka juga ikut diperhitungkan.",
  "E2m.tanya": "Berapa di antara saudara seayah itu yang beragama Islam {saat}?",
  "E2m.mengapa": "Hanya saudara yang seagama yang mewarisi atau mengurangi bagian ibu.",
  "E3.tanya": "Berapa saudara seibu (lain ayah) {pewaris} yang masih hidup {saat}?",
  "E3.mengapa": "Saudara seibu mendapat seperenam, atau berbagi sepertiga sama rata, bila tidak terhalang. Walaupun terhalang, dua saudara atau lebih tetap mengurangi bagian ibu.",
  "E3.bantuan": "Saudara seibu laki-laki dan perempuan mendapat bagian yang sama besar.",
  "E3m.tanya": "Berapa di antara saudara seibu itu yang beragama Islam {saat}?",
  "E3m.mengapa": "Hanya saudara yang seagama yang mewarisi atau mengurangi bagian ibu.",

  // --- F. Kerabat --------------------------------------------------------------------------
  "F1.tanya": "Apakah {pewaris} mempunyai keponakan laki-laki, yaitu anak laki-laki dari saudara laki-laki, yang masih hidup {saat}?",
  "F1.muslim.tanya": "Apakah {pewaris} mempunyai keponakan laki-laki yang beragama Islam, yaitu anak laki-laki dari saudara laki-laki, yang masih hidup {saat}?",
  "F1.mengapa": "Jika tidak ada anak laki-laki, ayah, kakek, atau saudara laki-laki, keponakan laki-laki menerima sisa harta.",
  "F1.bantuan": "Anak dari saudara perempuan atau dari saudara seibu tidak termasuk di sini.",
  "F1.opsi.kandung": "Ya, dari saudara laki-laki kandung",
  "F1.opsi.seayah": "Ya, hanya dari saudara laki-laki seayah",
  "F1.opsi.tidak": "Tidak ada",
  "F1n.tanya": "Berapa keponakan laki-laki itu?",
  "F1n.mengapa": "Sisa harta dibagi rata di antara mereka.",
  "F2.tanya": "Apakah {pewaris} mempunyai paman, yaitu saudara laki-laki dari ayah {pewaris}, yang masih hidup {saat}?",
  "F2.muslim.tanya": "Apakah {pewaris} mempunyai paman yang beragama Islam, yaitu saudara laki-laki dari ayah {pewaris}, yang masih hidup {saat}?",
  "F2.mengapa": "Paman dari pihak ayah menerima sisa bila tidak ada kerabat laki-laki yang lebih dekat.",
  "F2.bantuan": "Saudara laki-laki dari ibu tidak termasuk di sini.",
  "F2.opsi.kandung": "Ya, paman kandung (saudara kandung ayah)",
  "F2.opsi.seayah": "Ya, hanya paman seayah",
  "F2.opsi.tidak": "Tidak ada",
  "F2n.tanya": "Berapa paman itu?",
  "F2n.mengapa": "Sisa harta dibagi rata di antara mereka.",
  "F3.tanya": "Apakah {pewaris} mempunyai sepupu laki-laki, yaitu anak laki-laki dari paman pihak ayah, yang masih hidup {saat}?",
  "F3.muslim.tanya": "Apakah {pewaris} mempunyai sepupu laki-laki yang beragama Islam, yaitu anak laki-laki dari paman pihak ayah, yang masih hidup {saat}?",
  "F3.mengapa": "Sepupu laki-laki dari pihak ayah menerima sisa bila tidak ada kerabat laki-laki yang lebih dekat.",
  "F3.bantuan": "Anak dari bibi atau dari paman pihak ibu tidak termasuk di sini.",
  "F3.opsi.dari_kandung": "Ya, anak dari paman kandung",
  "F3.opsi.dari_seayah": "Ya, hanya anak dari paman seayah",
  "F3.opsi.tidak": "Tidak ada",
  "F3n.tanya": "Berapa sepupu laki-laki itu?",
  "F3n.mengapa": "Sisa harta dibagi rata di antara mereka.",
  "F5.tanya": "Apakah ada kerabat lain dari garis ayah yang masih hidup {saat}?",
  "F5.muslim.tanya": "Apakah ada kerabat lain dari garis ayah, yang beragama Islam, yang masih hidup {saat}?",
  "F5.mengapa": "Alat ini menghitung sampai anak saudara laki-laki dan sepupu. Bila kerabat yang lebih jauh bisa menerima sisa harta, kami akan menyarankan konsultasi.",
  "F5.bantuan": "Pilih semua yang ada.",
  "F5.opsi.keturunan_saudara": "Cucu atau cicit dari saudara, misalnya cucu dari saudara laki-laki",
  "F5.opsi.keturunan_paman": "Anak atau cucu dari sepupu",
  "F5.opsi.kerabat_ayah": "Paman atau sepupu dari ayah, atau kerabat ayah yang lebih jauh",
  "F4.tanya": "Apakah ada kerabat lain yang masih hidup {saat}, misalnya anak dari saudara perempuan, bibi, atau saudara dari ibu?",
  "F4.muslim.tanya": "Apakah ada kerabat lain yang beragama Islam dan masih hidup {saat}, misalnya anak dari saudara perempuan, bibi, atau saudara dari ibu?",
  "F4.mengapa": "Jika tidak ada ahli waris lain, kerabat ini (dzawil arham) bisa berhak. Perhitungannya khusus, jadi kami akan menyarankan konsultasi.",
  "F4.bantuan": "Jawab “Tidak” jika tidak ada kerabat lain sama sekali.",
  "F4.opsi.ya": "Ya",
  "F4.opsi.tidak": "Tidak",

  // --- G. Wasiat ---------------------------------------------------------------------------
  "G1.tanya": "Apakah {pewaris} meninggalkan wasiat, yaitu pesan pemberian harta setelah wafat?",
  "G1.mengapa": "Wasiat ditunaikan sebelum harta dibagi, paling banyak sepertiga harta, kecuali semua ahli waris setuju.",
  "G1.opsi.lain": "Ada, untuk orang lain atau lembaga",
  "G1.opsi.waris": "Ada, untuk salah satu ahli waris",
  "G2.tanya": "Untuk ahli waris yang mana wasiat itu?",
  "G2.mengapa": "Wasiat untuk ahli waris berlaku hanya bila ahli waris lain setuju.",
  "G3.tanya": "Berapa besar wasiat untuk orang lain atau lembaga itu?",
  "G3.mengapa": "Kami perlu tahu apakah wasiat melebihi sepertiga.",
  "G3.bantuan": "Jika wasiatnya berupa barang atau nilai tertentu, isi nilainya di panel rupiah pada laporan.",
  "G3.opsi.sepertiga": "Sepertiga harta",
  "G3.opsi.seperempat": "Seperempat harta",
  "G3.opsi.lebih_sepertiga": "Lebih dari sepertiga, misalnya setengah atau seluruh harta",
  "G3.opsi.nilai_tertentu": "Barang atau nilai tertentu",
  "G3w.tanya": "Berapa besar wasiat untuk ahli waris itu?",
  "G3w.mengapa": "Wasiat untuk ahli waris dilaksanakan hanya bila ahli waris lain setuju; bila tidak, wasiat itu tidak dihitung.",
  "G3w.opsi.sepertiga": "Sepertiga harta",
  "G3w.opsi.seperempat": "Seperempat harta",
  "G3w.opsi.lebih_sepertiga": "Lebih dari sepertiga, misalnya setengah atau seluruh harta",
  "G3w.opsi.nilai_tertentu": "Barang atau nilai tertentu",
  "G4.tanya": "Apakah semua ahli waris setuju wasiat ini dilaksanakan seluruhnya?",
  "G4.tanya_satu": "Apakah ahli waris setuju wasiat ini dilaksanakan seluruhnya?",
  "G4.mengapa": "Wasiat lebih dari sepertiga, atau untuk ahli waris, berlaku hanya bila ahli waris lain setuju.",
  "G4.opsi.setuju": "Setuju",
  "G4.opsi.tidak_setuju": "Tidak setuju",
  "G4.opsi.belum": "Belum dibicarakan",

  // --- roles (G2 picker, skip lines, family tree) ----------------------------------------------
  "peran.anak_lk": "Anak laki-laki",
  "peran.cucu_lk": "Cucu laki-laki (dari anak laki-laki)",
  "peran.ayah": "Ayah",
  "peran.kakek": "Kakek (ayah dari ayah)",
  "peran.sdr_lk_kandung": "Saudara laki-laki kandung",
  "peran.sdr_lk_seayah": "Saudara laki-laki seayah",
  "peran.sdr_lk_seibu": "Saudara laki-laki seibu",
  "peran.keponakan_lk_kandung": "Keponakan laki-laki (dari saudara laki-laki kandung)",
  "peran.keponakan_lk_seayah": "Keponakan laki-laki (dari saudara laki-laki seayah)",
  "peran.paman_kandung": "Paman kandung",
  "peran.paman_seayah": "Paman seayah",
  "peran.sepupu_lk_kandung": "Sepupu laki-laki (dari paman kandung)",
  "peran.sepupu_lk_seayah": "Sepupu laki-laki (dari paman seayah)",
  "peran.suami": "Suami",
  "peran.mutiq": "Mu'tiq",
  "peran.anak_pr": "Anak perempuan",
  "peran.cucu_pr": "Cucu perempuan (dari anak laki-laki)",
  "peran.ibu": "Ibu",
  "peran.nenek_ibu": "Nenek (ibu dari ibu)",
  "peran.nenek_ayah": "Nenek (ibu dari ayah)",
  "peran.sdr_pr_kandung": "Saudara perempuan kandung",
  "peran.sdr_pr_seayah": "Saudara perempuan seayah",
  "peran.sdr_pr_seibu": "Saudara perempuan seibu",
  "peran.istri": "Istri",
  "peran.mutiqah": "Mu'tiqah",
  "peran.pengganti": "Cucu pengganti orang tuanya",
  "peran.anak_lk_wafat": "Anak laki-laki yang wafat lebih dulu",
  "peran.anak_pr_wafat": "Anak perempuan yang wafat lebih dulu",
  "peran.cucu_dari_anak_pr": "Cucu dari anak perempuan",
  "peran.anak_angkat": "Anak angkat",
  "peran.anak_tiri": "Anak tiri",

  // --- groups not asked ("… tidak ditanyakan karena …") ---------------------------------------
  "kelompok.saudara": "Saudara",
  "kelompok.saudara_kandung": "Saudara kandung",
  "kelompok.saudara_seayah": "Saudara seayah",
  "kelompok.saudara_seibu": "Saudara seibu",
  "kelompok.keponakan": "Keponakan",
  "kelompok.paman": "Paman",
  "kelompok.sepupu": "Sepupu",
  "kelompok.kakek": "Kakek",
  "kelompok.nenek": "Nenek",
  "kelompok.cucu": "Cucu",
  "kelompok.kerabat_lain": "Kerabat lain",
  "lewati.karena": "{kelompok} tidak ditanyakan karena ada {penghalang}.",
  "lewati.tanpa_alasan": "{kelompok} tidak ditanyakan karena tidak mengubah pembagian.",

  // --- «Tidak tahu» readings, shown side by side (plan D15) -----------------------------------
  "bacaan.ada": "Jika ada",
  "bacaan.tidak_ada": "Jika tidak ada",
  "bacaan.satu": "Jika satu orang",
  "bacaan.dua_atau_lebih": "Jika dua orang atau lebih",
  "bacaan.muslim": "Jika semuanya beragama Islam",
  "bacaan.bukan_muslim": "Jika tidak semuanya beragama Islam",
  "bacaan.setuju": "Jika semua setuju",
  "bacaan.belum_setuju": "Jika belum setuju",

  // --- questionnaire notes ---------------------------------------------------------------
  "catatan.simulasi": "Ini simulasi: pembagian dihitung seolah-olah pewaris wafat hari ini. Keadaan keluarga bisa berubah.",
  "catatan.iddah": "Pasangan yang diceraikan dengan talak raj'i dan masih dalam masa iddah: apakah ia mewarisi perlu dipastikan. Laporan menunjukkan kedua kemungkinan.",
  "catatan.nikah_siri": "Pernikahan yang tidak dicatat: di Pengadilan Agama, pernikahan ini biasanya perlu diitsbatkan lebih dulu.",
  "catatan.anak_tiri": "Anak tiri bukan ahli waris. Ia tetap bisa diberi hibah atau wasiat.",
  "catatan.wasiat_tidak_diketahui": "Wasiat belum diketahui, jadi pembagian ditunjukkan tanpa wasiat. Bila ada wasiat, paling banyak sepertiga diambil lebih dulu.",
  "catatan.wasiat_perlu_nilai": "Nilai wasiat perlu diisi di panel rupiah agar wasiat ikut dihitung.",
  "catatan.hilang_tanpa_pengaruh": "Anggota keluarga yang hilang tidak mengubah pembagian ini, jadi perhitungan tetap dilanjutkan.",
  "catatan.kandungan_tanpa_pengaruh": "Bayi dalam kandungan tidak mengubah pembagian ini, jadi perhitungan tetap dilanjutkan.",
  "catatan.bersamaan_tanpa_pengaruh": "Anggota keluarga yang wafat bersamaan tidak mengubah pembagian ini, jadi perhitungan tetap dilanjutkan.",
  "catatan.pasangan_terdahulu": "Ada pasangan terdahulu: pembagian tetap dihitung, tetapi harta bersama perlu dipisahkan lebih dulu di pengadilan.",
  "catatan.pasangan_terdahulu_tidak_tahu": "Belum diketahui apakah ada pasangan terdahulu: harta bersama perlu dipastikan lebih dulu.",
  "catatan.harta_bersama_terdahulu_tidak_tahu":
    "Belum diketahui apakah harta bersama dari pernikahan terdahulu sudah dibagi: harta bersama perlu dipastikan lebih dulu.",

  // --- exits ("Konsultasikan", plan §5.4) -------------------------------------------------------
  "exit.E-HIDUP.judul": "Ini hibah, bukan waris",
  "exit.E-HIDUP.situasi": "Harta seseorang yang masih hidup tidak dibagi sebagai warisan. Pemberian semasa hidup disebut hibah.",
  "exit.E-HIDUP.alasan": "Waris baru berlaku setelah seseorang wafat. Semasa hidup, Anda dapat memberi hibah dengan adil di antara anak-anak, dan menulis wasiat paling banyak sepertiga untuk selain ahli waris.",
  "exit.E-HIDUP.langkah": "Tuliskan wasiat Anda dan simpan bersama dokumen keluarga. Untuk melihat gambaran pembagian, lanjutkan sebagai simulasi.",
  "exit.E-NONMUSLIM.judul": "Di luar cakupan alat ini",
  "exit.E-NONMUSLIM.situasi": "Harta seseorang yang wafat bukan Muslim tidak dibagi menurut hukum waris Islam.",
  "exit.E-NONMUSLIM.alasan": "Kompilasi Hukum Islam berlaku untuk pewaris yang beragama Islam, sehingga perkaranya bukan di Pengadilan Agama.",
  "exit.E-NONMUSLIM.langkah": "Konsultasikan dengan pengadilan negeri atau penasihat hukum. Kerabat yang Muslim tetap bisa menerima hibah atau wasiat.",
  "exit.E-BUNUH.judul": "Perlu dikonsultasikan langsung",
  "exit.E-BUNUH.situasi": "Bila ada anggota keluarga yang menyebabkan wafatnya pewaris, pembagian waris tidak dapat dihitung sendiri.",
  "exit.E-BUNUH.alasan": "Orang yang menyebabkan wafatnya pewaris tidak mewarisi, dan menurut Kompilasi Hukum Islam hal ini ditetapkan dengan putusan pengadilan. Jawaban ini tidak kami simpan.",
  "exit.E-BUNUH.langkah": "Konsultasikan dengan ustadz atau ahli faraid, dan dengan Pengadilan Agama.",
  "exit.E-KHUNTSA.judul": "Perlu dikonsultasikan",
  "exit.E-KHUNTSA.situasi": "Ada ahli waris yang jenis kelaminnya tidak dapat dipastikan.",
  "exit.E-KHUNTSA.alasan": "Bagian ahli waris bergantung pada jenis kelaminnya, dan perhitungan untuk keadaan ini perlu ditetapkan oleh ahlinya.",
  "exit.E-KHUNTSA.langkah": "Konsultasikan dengan ustadz atau ahli faraid, atau dengan Pengadilan Agama.",
  "exit.E-MAFQUD.judul": "Perlu dikonsultasikan",
  "exit.E-MAFQUD.situasi": "Ada anggota keluarga yang hilang, dan ia bisa mengubah pembagian.",
  "exit.E-MAFQUD.alasan": "Bagian orang yang hilang ditahan sampai pengadilan menyatakan ia telah wafat. Alat ini tidak menebak keadaannya.",
  "exit.E-MAFQUD.langkah": "Mintalah penetapan dari Pengadilan Agama, lalu hitung kembali.",
  "exit.E-HAML.judul": "Perlu dikonsultasikan",
  "exit.E-HAML.situasi": "Ada bayi dalam kandungan yang bisa mengubah pembagian.",
  "exit.E-HAML.alasan": "Bayi yang lahir hidup ikut mewarisi, dan bagiannya bergantung pada jenis kelamin dan jumlahnya. Biasanya pembagian ditunda sampai bayi lahir.",
  "exit.E-HAML.langkah": "Tunggu sampai bayi lahir, lalu hitung kembali, atau konsultasikan dengan ustadz atau ahli faraid.",
  "exit.E-BERSAMAAN.judul": "Perlu dikonsultasikan",
  "exit.E-BERSAMAAN.situasi": "Beberapa anggota keluarga wafat dalam satu musibah tanpa diketahui siapa yang lebih dulu, dan hal ini bisa mengubah pembagian.",
  "exit.E-BERSAMAAN.alasan": "Mereka yang wafat bersamaan tidak saling mewarisi; harta masing-masing dibagi kepada ahli warisnya sendiri yang masih hidup.",
  "exit.E-BERSAMAAN.langkah": "Hitung harta setiap orang secara terpisah, atau konsultasikan dengan ustadz atau ahli faraid.",
  "exit.E-KERABAT-JAUH.judul": "Perlu dikonsultasikan",
  "exit.E-KERABAT-JAUH.situasi": "Ada kerabat yang lebih jauh dari cucu, keponakan, atau sepupu, dan ia bisa mengubah pembagian.",
  "exit.E-KERABAT-JAUH.alasan": "Alat ini hanya menghitung sampai cucu, kakek dan nenek, anak saudara laki-laki, dan sepupu dari pihak ayah. Kerabat yang lebih jauh perlu diperiksa langsung.",
  "exit.E-KERABAT-JAUH.langkah": "Konsultasikan dengan ustadz atau ahli faraid, atau dengan Pengadilan Agama.",
  "exit.E-DZAWIL.judul": "Perlu dikonsultasikan",
  "exit.E-DZAWIL.situasi": "Yang tersisa adalah kerabat yang bukan penerima bagian tetap maupun penerima sisa (dzawil arham).",
  "exit.E-DZAWIL.alasan": "Perhitungan untuk kerabat ini khusus dan pendapat ulama tentangnya berbeda, jadi alat ini belum menghitungnya.",
  "exit.E-DZAWIL.langkah": "Konsultasikan dengan ustadz atau ahli faraid, atau dengan Pengadilan Agama.",
  "exit.E-TANPA-AHLI-WARIS.judul": "Tidak ada ahli waris",
  "exit.E-TANPA-AHLI-WARIS.situasi": "Tidak ada pasangan atau kerabat yang dapat menjadi ahli waris.",
  "exit.E-TANPA-AHLI-WARIS.alasan": "Menurut Kompilasi Hukum Islam, bila tidak ada ahli waris sama sekali, harta diserahkan melalui putusan Pengadilan Agama kepada Baitul Mal untuk kepentingan agama Islam dan kesejahteraan umum.",
  "exit.E-TANPA-AHLI-WARIS.langkah": "Ajukan permohonan ke Pengadilan Agama. Bila ada wasiat lebih dari sepertiga, konsultasikan lebih dulu.",
  "exit.E-UTANG.judul": "Utang melebihi harta",
  "exit.E-UTANG.situasi": "Utang dan biaya yang dimasukkan sama dengan atau melebihi harta peninggalan.",
  "exit.E-UTANG.alasan": "Utang dibayar lebih dulu dari harta. Bila harta tidak cukup, tidak ada yang tersisa untuk dibagi, dan penyelesaiannya perlu dibicarakan.",
  "exit.E-UTANG.langkah": "Periksa kembali nilai yang dimasukkan, lalu konsultasikan dengan Pengadilan Agama atau penasihat hukum.",
  "exit.E-TIDAK-TAHU.judul": "Perlu dipastikan dulu",
  "exit.E-TIDAK-TAHU.situasi": "Jawaban “Tidak tahu” pada pertanyaan berikut mengubah pembagian, sehingga kami tidak dapat menunjukkan satu hasil yang pasti.",
  "exit.E-TIDAK-TAHU.alasan": "Kami tidak menebak keadaan keluarga, karena tebakan bisa menambah atau menghapus ahli waris dalam laporan.",
  "exit.E-TIDAK-TAHU.langkah": "Pastikan jawabannya, lalu ubah jawaban Anda, atau konsultasikan dengan ustadz atau ahli faraid.",
  "exit.E-RUJUK.judul": "Perlu dikonsultasikan",
  "exit.E-RUJUK.situasi": "Keadaan keluarga ini tidak dapat dihitung oleh alat ini.",
  "exit.E-RUJUK.alasan": "Perhitungannya bergantung pada hal yang perlu ditetapkan oleh ahlinya.",
  "exit.E-RUJUK.langkah": "Konsultasikan dengan ustadz atau ahli faraid, atau dengan Pengadilan Agama.",
  "exit.E-HIDUP.lanjut": "Lanjutkan sebagai simulasi: jika saya wafat hari ini",
} as const;

export type QTextKey = keyof typeof Q_TEXT;

export function isQTextKey(k: string): k is QTextKey {
  return Object.prototype.hasOwnProperty.call(Q_TEXT, k);
}

/** Fill {placeholders} (for tests and the plain-text summary; the UI uses next-intl). */
export function fill(key: QTextKey, vars: Readonly<Record<string, string>>): string {
  return Q_TEXT[key].replace(/\{([A-Za-z]+)\}/g, (m, name: string) => (name in vars ? vars[name] : m));
}
